### ISSUE TITLE
Cannot read property 'add' of undefined

### ISSUE THREAD

**Issue by br0k3n** [usablica/kissui.scrollanim#10]
Hi,

adding this script my site return the error below:

Uncaught TypeError: Cannot read property 'add' of undefined @ scrollanim.js?ver=4.6:66

and no animation works :(

Please, could you help me?
Thanks so much

**Comment by rodoneill** [comment]
Where are you including the js file, in the head or just before the end of your closing body tag?

**Comment by br0k3n** [comment]
Hi,
in my footer, with all the others js files

Thanks

**Comment by br0k3n** [comment]
If I move the script into the header there's a new error:

scrollanim.js?ver=4.6:155 Uncaught TypeError: Cannot read property 'on' of undefined

Here's the url: http://goo.gl/gSH1vw

Thanks

**Comment by br0k3n** [comment]
Hi, any idea?

Thanks

**Comment by afshinm** [comment]
will have a look into this today guys, thanks for the report.

**Comment by br0k3n** [comment]
Thanks you :)
Let us know

**Comment by br0k3n** [comment]
Hi, any news?

Thanks

**Comment by afshinm** [comment]
sorry for the delay @br0k3n 

I have reviewed the code again and all seem fine. can you please use this source from CDNJS and let me know if you still have the issue: 

https://cdnjs.com/libraries/kissui.scrollanim

thanks
