### ISSUE TITLE
setOption and setOptions missing on scrollAnim.js (but not minified version)

### ISSUE THREAD

**Issue by remotesynth** [usablica/kissui.scrollanim#13]
So, here's something I noticed in my testing, but managed to see it also exists in your example (screenshot attached). The unminified version of scrollAnim.js does not have setOptions or setOption. However, the minified version seems to have it. I only noticed as I was writing a demo and prefer to work with the unminified version as I do testing and learn a library.

<img width="1008" alt="screen shot 2016-09-02 at 2 00 52 pm" src="https://cloud.githubusercontent.com/assets/216712/18213382/e8d70b70-7115-11e6-92e7-0f0b33d47c68.png">

**Comment by afshinm** [comment]
hey, it's available but I haven't updated the website's JS files yet. use the CDN or manual download.

**Comment by remotesynth** [comment]
I had used the manual download, so that's not updated either.
