### ISSUE TITLE
Is it possible to revert animation when scroll up?

### ISSUE THREAD

**Issue by katopz** [usablica/kissui.scrollanim#4]
e.g. it's scroll from left to right when scroll down 
and it'll automatic revert animation right to left when user scroll up?

BTW, it's HW accelerated on all device am I right?

**Comment by afshinm** [comment]
Hey @katopz 

Sorry, I didn't get exactly what you meant. Can you please explain in detail?

re HW accelerated: yes.

**Comment by katopz** [comment]
@afshinm Sorry for confusion, I'm asking because your demo only show `play once` and `loop` so I'm not sure I can go backward and forward like this http://lab.hakim.se/reveal-js/#/10/1 or this http://impress.github.io/impress.js/#/ing which will replay (revert animation) when back to previous page.

**Comment by afshinm** [comment]
hey @katopz, got it. this is a good idea! we don't have this at the moment but I'm going to add the feature label to this to add it to the next release.

Cheers.

**Comment by afshinm** [comment]
just added this to v0.3.0
