### ISSUE TITLE
Convert css to sass file

### ISSUE THREAD

**Issue by geosigno** [usablica/kissui.scrollanim#7]
Would it be possible to translate the animation.css to sass. Then we would be able to chose only style we need.
For example, in my case, I only use fadeIn style, but still the css file is 55ko.

**Comment by afshinm** [comment]
We don't have an internal css file and I think it would be possible to replace a sass version of animate.css. I'm marking this as a enhancement.

**Comment by afshinm** [comment]
sorry for the delay @geosenna. we don't have any css files and we are just using the animate.css for animations. Googled and found this one: https://github.com/geoffgraham/animate.scss

Hope this helps.
